### ISSUE TITLE
Example/Documentation

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/SBMLimporter#1]
give an example of how and where to start using the importer

**Comment by thomassligon** [comment]
There are two examples of this in GenSSI:
https://github.com/genssi-developer/GenSSI/blob/master/Examples/BIOMD0000000003/runBIOMD0000000003.m
https://github.com/genssi-developer/GenSSI/blob/master/Examples/BIOMD0000000010/runBIOMD0000000010.m
...and, of course, in AMICI:
https://github.com/ICB-DCM/AMICI/blob/master/SBML2AMICI.m

**Comment by yannikschaelte** [comment]
Thanks Thomas, your links should suffice (I was just thinking that in the SBMLimporter project there is no documentation about this).
