### ISSUE TITLE
importSBML no longer working in current MATLAB version

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/SBMLimporter#2]
This was https://github.com/AMICI-dev/AMICI/issues/1875.

In MATLAB Version: 9.8.0.1873465 (R2020a) Update 8 and libSBML 5.19.0. AMICI importSBML fails with error
Error using sym>convertChar (line 1546)
Character vectors and strings in the first argument can only specify a variable or number. To evaluate character
vectors and strings representing symbolic expressions, use 'str2sym'.

As a result, genSSI can no longer import SBML models.

This is related to AMICI issue https://github.com/AMICI-dev/AMICI/issues/234, which was fixed 5 years ago. https://github.com/AMICI-dev/AMICI/issues/234
It is also related (and documented) in the new libSBML issue 274. https://github.com/sbmlteam/libsbml/issues/274

This can be reproduced by running genSSI runExample('BIOMD0000000003').

A straightforward fix to this is described in https://github.com/sbmlteam/libsbml/issues/274.

**Comment by thomassligon** [comment]
In GenSSI, analysing the two models BIOMD0000000003 and MIOMD0000000010 now works in MATLAB R2020a after changing 3 lines in SBMLimporter/@SBMLode/importSBML.m.
How can we make sure that this is tested where necessary?

**Comment by FFroehlich** [comment]
Hi Tom, you can simply make a pull request here. We don't have any tests specifically for the importer as we used to test this directly in AMICI. Unfortunately, I don't think this will fix issues in amici since https://github.com/AMICI-dev/AMICI/blob/57a7b11cc2fb301cf838daefd966830c522643a8/matlab/%40optsym/optsym.m also broke with the R2018a update.

**Comment by thomassligon** [comment]
I created a pull request called Issue #2.

**Comment by thomassligon** [comment]
Hello Fabian, I see that you approved the pull request. What is the next step, and who needs to take it?

**Comment by thomassligon** [comment]
That fixes the problem in importSBML detected while testing https://github.com/genssi-developer/GenSSI/issues/19.
